<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Other Test"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="0.015">
  <properties />
            <testcase name="testAsserts" time="0.001" classname="com.simplilearn.testng.Phase2_Selenium_TestNG.AssertionTest">
                <failure type="java.lang.AssertionError"
                  message="did not expect [Vikram] but found [Vikram]"
              >
<![CDATA[java.lang.AssertionError: did not expect [Vikram] but found [Vikram]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failEquals(Assert.java:1582)
  org.testng.Assert.assertNotEqualsImpl(Assert.java:157)
  org.testng.Assert.assertNotEquals(Assert.java:2198)
  org.testng.Assert.assertNotEquals(Assert.java:2220)
  com.simplilearn.testng.Phase2_Selenium_TestNG.AssertionTest.testAsserts(AssertionTest.java:25)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:848)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
  org.testng.SuiteRunner.run(SuiteRunner.java:336)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
  org.testng.TestNG.runSuites(TestNG.java:1114)
  org.testng.TestNG.run(TestNG.java:1082)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="hardAssertTest" time="0.003" classname="com.simplilearn.testng.Phase2_Selenium_TestNG.AssertionTest" />
                <testcase name="softAssertTest" time="0.011" classname="com.simplilearn.testng.Phase2_Selenium_TestNG.AssertionTest" />
      
</testsuite>
